# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

###############################################################################
# Base box                                                                    #
###############################################################################
    config.vm.box              = "puppetlabs/centos-6.6-64-puppet"
    config.vm.box_version      = '1.0.1'
    config.vm.box_check_update = false

###############################################################################
# Global plugin settings                                                      #
###############################################################################
    plugins = ["vagrant-hostmanager"]
    plugins.each do |plugin|
      unless Vagrant.has_plugin?(plugin)
        raise plugin << " has not been installed."
      end
    end

    # Configure cached packages to be shared between instances of the same base box.
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :machine
    end

    # When destroying a node, delete the node from the puppetmaster
    if Vagrant.has_plugin?("vagrant-triggers")
      config.trigger.after [:destroy] do
        target = @machine.config.vm.hostname.to_s
        puppetmaster = "puppetmaster"
        if target != puppetmaster
          system("vagrant ssh #{puppetmaster} -c 'sudo /usr/bin/puppet cert clean #{target}'" )
        end
      end
    end

###############################################################################
# Global provisioning settings                                                #
###############################################################################
    env = 'xs'

###############################################################################
# Global VirtualBox settings                                                  #
###############################################################################
    config.vm.provider 'virtualbox' do |v|
    v.customize [
      'modifyvm', :id,
      '--groups', '/Vagrant/puppetmaster'
    ]
    end

###############################################################################
# Global /etc/hosts file settings                                             #
###############################################################################
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

###############################################################################
# VM definitions                                                              #
###############################################################################
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define :puppetmaster do |puppetmaster_config|
      puppetmaster_config.vm.host_name = "puppetmaster.#{env}.vagrant"
      puppetmaster_config.vm.network :private_network, ip: "192.168.26.130"
      puppetmaster_config.vm.network :forwarded_port, guest: 22, host: 2630
      puppetmaster_config.vm.synced_folder '../../manifests/', "/etc/puppet/environments/#{env}/manifests"
      puppetmaster_config.vm.synced_folder '../../modules/', "/etc/puppet/environments/#{env}/modules"
      puppetmaster_config.vm.synced_folder '../../hiera/', '/var/lib/hiera'
      puppetmaster_config.vm.provision :puppet do |puppet|
          puppet.options           = "--environment #{env}"
          puppet.manifests_path    = "../../manifests"
          puppet.manifest_file     = ""
          puppet.module_path       = "../../modules"
          puppet.hiera_config_path = "../../files/hiera.yaml"
      end
    end

    config.vm.define :puppetdb do |puppetdb_config|
      puppetdb_config.vm.host_name = "puppetdb.l.vagrant"
      puppetdb_config.vm.network :forwarded_port, guest: 22, host: 2631
      puppetdb_config.vm.network :private_network, ip: "192.168.26.131"
      node_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t"
        puppet.puppet_server = "compile.#{env}.vagrant"
      end
    end

    config.vm.define :foreman do |foreman_config|
      foreman_config.vm.host_name = "foreman.l.vagrant"
      foreman_config.vm.network :forwarded_port, guest: 22, host: 2632
      foreman_config.vm.network :private_network, ip: "192.168.26.132"
      foreman_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t"
        puppet.puppet_server = "compile.#{env}.vagrant"
      end
    end

    config.vm.define :foreman do |foreman_config|
      foreman_config.vm.host_name = "foreman.l.vagrant"
      foreman_config.vm.network :forwarded_port, guest: 22, host: 2633
      foreman_config.vm.network :private_network, ip: "192.168.26.133"
      foreman_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t"
        puppet.puppet_server = "compile.#{env}.vagrant"
      end
    end

    config.vm.define :activemq do |activemq_config|
      activemq_config.vm.host_name = "activemq.l.vagrant"
      activemq_config.vm.network :forwarded_port, guest: 22, host: 2634
      activemq_config.vm.network :private_network, ip: "192.168.26.134"
      activemq_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t"
        puppet.puppet_server = "compile.#{env}.vagrant"
      end
    end

    config.vm.define :compile do |compile_config|
      compile_config.hostmanager.aliases = %w(compile.#{env}.vagrant puppet)
      compile_config.vm.host_name = "compile.#{env}.vagrant"
      compile_config.vm.network :forwarded_port, guest: 22, host: 1939
      compile_config.vm.network :private_network, ip: "192.168.26.139"
      compile_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t --environment #{env}"
        puppet.puppet_server = "puppetmaster.#{env}.vagrant"
      end
      compile_config.vm.provision :shell, inline: R10K
    end

    config.vm.define :node do |node_config|
      node_config.vm.host_name = "node.#{env}.vagrant"
      node_config.vm.network :forwarded_port, guest: 22, host: 1940
      node_config.vm.network :private_network, ip: "192.168.26.140"
      node_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t"
        puppet.puppet_server = "compile.#{env}.vagrant"
      end
    end
end
