# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

###############################################################################
# Base box                                                                    #
###############################################################################
    config.vm.box              = "puppetlabs/centos-7.2-64-puppet"

###############################################################################
# Global plugin settings                                                      #
###############################################################################
    plugins = ["vagrant-hostmanager"]
    plugins.each do |plugin|
      unless Vagrant.has_plugin?(plugin)
        raise plugin << " has not been installed."
      end
    end

    # Configure cached packages to be shared between instances of the same base box.
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :machine
    end

    # When destroying a node, delete the node from the puppetmaster
    if Vagrant.has_plugin?("vagrant-triggers")
      config.trigger.after [:destroy] do
        target = @machine.config.vm.hostname.to_s
        puppetmaster = "puppetmaster"
        if target != puppetmaster
          system("vagrant ssh #{puppetmaster} -c 'sudo /opt/puppetlabs/bin/puppet cert clean #{target}'" )
        end
      end
    end

###############################################################################
# Global provisioning settings                                                #
###############################################################################
    env = 'xxs'

###############################################################################
# Global VirtualBox settings                                                  #
###############################################################################
    config.vm.provider 'virtualbox' do |v|
    v.customize [
      'modifyvm', :id,
      '--groups', '/Vagrant/puppetmaster'
    ]
    end

###############################################################################
# Global /etc/hosts file settings                                             #
###############################################################################
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

###############################################################################
# VM definitions                                                              #
###############################################################################
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define :puppetmaster do |puppetmaster_config|
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096 
        vb.cpus   = 2
      end
      puppetmaster_config.vm.host_name = "puppetmaster.#{env}.vagrant"
      puppetmaster_config.vm.network :private_network, ip: "192.168.21.130"
      puppetmaster_config.vm.network :forwarded_port, guest: 22, host: 2130
      puppetmaster_config.vm.synced_folder '../../puppet/manifests/', "/etc/puppetlabs/code/environments/#{env}/manifests"
      puppetmaster_config.vm.synced_folder '../../puppet/modules/', "/etc/puppetlabs/code/environments/#{env}/modules"
      puppetmaster_config.vm.synced_folder '../../puppet/hieradata', "/etc/puppetlabs/code/environments/#{env}/hieradata"
      puppetmaster_config.vm.provision :puppet do |puppet|
          puppet.environment = "#{env}"
          puppet.environment_path = "../../"
          puppet.hiera_config_path = "../../puppet/hiera.yaml"
      end
    end

    config.vm.define :node do |node_config|
      node_config.vm.host_name = "node.#{env}.vagrant"
      node_config.vm.network :forwarded_port, guest: 22, host: 2140
      node_config.vm.network :private_network, ip: "192.168.21.140"
      node_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t --environment #{env}"
        puppet.puppet_server = "puppetmaster.#{env}.vagrant"
      end
    end
end
