# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  ###############################################################################
  # Global plugin settings                                                      #
  ###############################################################################
  plugins = ["vagrant-hostmanager"]
  plugins.each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      raise plugin << " has not been installed."
    end
  end
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
  end

  if Vagrant.has_plugin?("vagrant-puppet-install")
    config.puppet_install.puppet_version = :latest
  end

  ###############################################################################
  # Global provisioning settings                                                #
  ###############################################################################
  config.vm.box = "bento/centos-7.2"
  env = 'xs'

  ###############################################################################
  # Global VirtualBox settings                                                  #
  ###############################################################################
  config.vm.provider 'virtualbox' do |v|
  v.customize [
    'modifyvm', :id,
    '--groups', '/Vagrant/puppetmaster'
  ]
  end

  ###############################################################################
  # VM definitions                                                              #
  ###############################################################################
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define :puppetmaster do |puppetmaster_config|
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus   = 2
      end
      puppetmaster_config.vm.host_name = "puppetmaster.#{env}.vagrant"
      puppetmaster_config.vm.network :private_network, ip: "192.168.22.130"
      puppetmaster_config.vm.network :forwarded_port, guest: 22, host: 2230
      puppetmaster_config.vm.synced_folder '../../production/manifests/', "/etc/puppetlabs/code/environments/#{env}/manifests"
      puppetmaster_config.vm.synced_folder '../../production/modules/', "/etc/puppetlabs/code/environments/#{env}/modules"
      puppetmaster_config.vm.synced_folder '../../production/hieradata', "/etc/puppetlabs/code/environments/#{env}/hieradata"
      puppetmaster_config.vm.provision :puppet do |puppet|
          puppet.environment = "#{env}"
          puppet.environment_path = "../../"
          puppet.hiera_config_path = "../../production/hiera.yaml"
      end
    end

    config.vm.define :node do |node_config|
      node_config.vm.host_name = "node.#{env}.vagrant"
      node_config.vm.network :forwarded_port, guest: 22, host: 2240
      node_config.vm.network :private_network, ip: "192.168.22.140"
      node_config.vm.provision "puppet_server" do |puppet|
        puppet.options       = "-t --environment #{env}"
        puppet.puppet_server = "puppetmaster.#{env}.vagrant"
      end
    end
end
